[package]
name = "ori-archipelago-hint"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.2"
egui = "0.33.2"
egui_extras = "0.33.2"
env_logger = "0.11.8"
json = "0.12.4"
rand = "0.9.2"
rand_chacha = "0.9.0"
regex = "1.12.2"
serde = "1.0.228"
serde_json = "1.0.145"
